#index:
#    path: /
#    controller: App\Controller\DefaultController::index

## the "app_hello_world" route name is not important yet
#app_hello_world:
#    path: /hello/world
#    controller: App\Controller\HelloWorldController::hello